# Machine Learning Lab 02

For this lab, you can find sections for NumPy, Pandas, Matplotlib, Exploratory Data Analysis, and the optional Analysis of Anscombe's Quartet.

Please add new cells for your code to expand this notebook (**File** --> **Insert**)

## NumPy

In [11]:
# 1.2 - Creating NumPy arrays

import numpy as np

an_array = np.array([])
another_array = np.array([0,1,2,3,4,3,2,1,0,3])
an_array = np.append(an_array, another_array)
print(an_array)

c = np.array([(1,3,3,7),(4,2,4,2)])
print(c)

[0. 1. 2. 3. 4. 3. 2. 1. 0. 3.]
[[1 3 3 7]
 [4 2 4 2]]


In [16]:
# 1.3 - Accessing data in arrays

print('3rd value (at index 2):',another_array[2])
print("Value at (0, 2) =", c[0][2])
print("1st row =", c[0])
print("2nd column =", c[:,1])
print("2nd column (up to 1st row) =", c[:1,1])
print("2nd column (up to 5th row) =", c[:5,1])

3rd value (at index 2): 2
Value at (0, 2) = 3
1st row = [1 3 3 7]
2nd column = [3 2]
2nd column (up to 1st row) = [3]
2nd column (up to 5th row) = [3 2]


In [20]:
# 1.4 - Iterating over arrays

for i in range(another_array.size):
    print(another_array[i])
print("---------------")

for value in another_array:
    print(value)
print("---------------")

for row in c:
    print(row)
print("---------------")

print("Iterating over each element, row by row")
for row in c:
    for cell in row:
        print(cell, end=' ')
print("\n---------------")

print("Iterating over each element, using flatten function")
for cell in c.flatten():
    print(cell, end=' ')

0
1
2
3
4
3
2
1
0
3
---------------
0
1
2
3
4
3
2
1
0
3
---------------
[1 3 3 7]
[4 2 4 2]
---------------
Iterating over each element, row by row
1 3 3 7 4 2 4 2 
---------------
Iterating over each element, using flatten function
1 3 3 7 4 2 4 2 

In [ ]:
# 1.5 - NumPy functions and attributes



## SciPy

## Pandas

## Matplotlib

## Exploratory Data Analysis

Some of the cells below already got code doing things for you.

Some cells are empty for you to do _stuff_ in to **answer questions**!

See lab task notes for the list of questions if you want to see them all in one place.

### Loading the dataset

First, we load the dataset, then we can execute various functions to explore the data, calculate statistics and plot graphs.

In [ ]:
import pandas as pd

dataset = pd.read_csv('data/ml-assessment-dataset.csv')
dataset.head()

### Exploring the dataset

The overall aim for the data exploration here is to get a feel for some of the influences on the machine learning marks for past students.

Let's focus on two features for this:
 * Class (1 = pass, 0 = fail)
 * Total mark (the total unit mark, range 0-100)
 * L4 mean mark (to mean mark across all 6 level 4 units)

#### General information

Questions to answer:
* How many instances are there in the dataset?
* What is the mean mark (total), including non-submissions?

In [ ]:
# TODO: answer the two questions with the following functions
# .info()
# .describe()



#### Class (pass/fail) analysis

Questions to answer:
* Is the class balance equal?
* Which class is the MOST represented in the dataset?
* How many students passed?

In [ ]:
# TODO: NUMERIC OUTPUT FOR CLASS BALANCE (NUMBER OF VALUES/INSTANCES FOR EACH CLASS)


In [ ]:
# TODO: CHART FOR CLASS DISTRIBUTION


#### Mark analysis

Questions to answer:

* What is the mean mark (total), including non-submissions?
* What is the mean mark (total), excluding non-submissions?
* What is the mean level 4 mark for the students who passed?
* What is the mean level 4 mark for the students who failed?

In [ ]:
# To get the mean of a specific feature/column, you can use this format:
#   dataset['COLUMN_NAME'].mean()



In [ ]:
# Have a go at using one of these functions for the first 2 questions
#
#    dataset['COLUMN_NAME_FOR_THE_VALUES_YOU_WANT'][dataset['COLUMN_NAME_TO_FILTER_BY'] == FILTER_VALUE_YOU_WANT].mean()
#    dataset.groupby('COLUMN_NAME_TO_GROUP_BY')['COLUMN_NAME_FOR_THE_VALUES_YOU_WANT'].mean()
#
# For example, the following would print out the mean age of ANYBODY (female and male) without heart diseas
#
#    print(dataset['Total mark'][dataset['Class'] == 0].mean())
#    print(dataset.groupby('Class')['Total mark'].mean())
#
# In the examples above, you want to find out the mean ages for genders, not the class (for the first 2 questions)
# Remember, column names are case sensitive

# TODO: Mean mark for those submitted (excluding non-submissions)



# TODO: Mean level 4 mark for those students who passed vs failed



## Analysis of Anscombe's Quartet

There are many ways you can play around with the data and have a look at it, e.g.,

1. a hardcoded approach using numpy and matplotlib
2. an approach using pandas and reading directly from Excel

The example code below uses option 1 just to keep it simpler here.

In [ ]:
import numpy as np
from scipy import stats
from numpy.polynomial.polynomial import polyfit
import matplotlib.pyplot as plt

# Anscombe's 1st dataset
x1 = np.array([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5])
y1 = np.array([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68])

# Anscombe's 2nd dataset
x2 = np.array([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5])
y2 = np.array([9.14, 8.14, 8.74, 8.77, 9.26, 8.1, 6.13, 3.1, 9.13, 7.26, 4.74])

# TODO: Anscombe's 3rd dataset


# TODO: Anscombe's 4th dataset



### Print out the stats

* mean
* median
* mode
* variance
* standard deviation

In [ ]:
print("Anscombe stats\n")
# TODO (using Numpy and SciPy)



### Plot regression lines

This is more challenging, but you can use the following code as the basis for:

* Calculate/create regression lines for the 3rd and 4th datasets (that you added above)
* Change the subplot configuration to a 2 x 2 grid (currently 1 x 2)
* Plot the 3rd and 4th datasets (as subplots with the 1st and 2nd datasets)

**REFLECT** on the stats above and what you see in the images.

In [ ]:
# Linear regression lines
b1, m1 = polyfit(x1, y1, 1)
b2, m2 = polyfit(x2, y2, 1)

# Setting up figure with two sub-plots
fig, axs = plt.subplots(1, 2, figsize=(16, 6), sharey=True)
fig.suptitle("Anscombe's Quartet")

# Adding figure for Ans-1
axs[0].plot(x1, y1, '.')
axs[0].plot(x1, b1 + m1 * x1, '-')
axs[0].set_xlabel('x')
axs[0].set_ylabel('y')

# Adding figure for Ans-2
axs[1].plot(x2, y2, '.')
axs[1].plot(x2, b2 + m2 * x2, '-')
axs[0].set_xlabel('x')
axs[0].set_ylabel('y')