<a href="https://colab.research.google.com/github/bu-ml-bonus/ml-bonus-02---python-revision-LithiumDrache/blob/main/ml-bonus-02-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning Bonus 2 - Python


You can do the python practice for this lab in what ever IDE you want, but you are encouraged to get familiar with using Jupyter Notebooks, so you can do both at the same time ;)

To run code in a cell, just click the cell and hit **SHIFT + ENTER**.

Or... Press the **run** button (play icon when you hover the mouse over a cell).

Alternatively, to run **all** the cells in the notebook.

* In Google Colab: go to the file menu --> **Runtime** --> **Run All**.

* In native Jupyter: go to the file menu --> **Cell** --> **Run All**.

## Variables

You can create more cells within the coding sections by going to the file menu: **Insert** --> **Code Cell**.

**PS**: worth noting the keyboard shortcut for doing that.

In [12]:
a_variable = 10
print("a_variable =", a_variable, "- type", type(a_variable))
print("a_avriable =", a_variable+10, "- type", type(a_variable))

a_variable = 10 + 10.0
print("a_avriable =", a_variable, "- type", type(a_variable))

a_variable = 10
another_variable = a_variable
print("another_variable =", another_variable, "- type", type(another_variable))

another_variable = 'machine'
print("another_variable =", another_variable, "- type", type(another_variable))
print("another_variable =", another_variable+' learning', "- type", type(another_variable))
print("another_variable =", another_variable+'\n\tlearning', "- type", type(another_variable))

boolean_variable = True
another_boolean_variable = not boolean_variable
print(boolean_variable, "\n",  another_boolean_variable)

a_variable = 10 - type <class 'int'>
a_avriable = 20 - type <class 'int'>
a_avriable = 20.0 - type <class 'float'>
another_variable = 10 - type <class 'int'>
another_variable = machine - type <class 'str'>
another_variable = machine learning - type <class 'str'>
another_variable = machine
	learning - type <class 'str'>
True 
 False


## Data structures



In [26]:
# 1D Array - Python

mylist = []
print (mylist)

mylist = ["Li","Dom","Charlie","Miles","Tom","Ollie"]
print (mylist)

print (mylist[1])

mylist[2] = "Charles"
print (mylist)

[]
['Li', 'Dom', 'Charlie', 'Miles', 'Tom', 'Ollie']
Dom
['Li', 'Dom', 'Charles', 'Miles', 'Tom', 'Ollie']


In [25]:
# 1D Array - Numpy
import numpy

arr = numpy.array([])
print (arr)

arr = numpy.array(["Li","Dom","Charlie","Miles","Tom","Ollie"])
print (arr)

print (arr[1])

arr[2] = "Charles"
print (arr)

[]
['Li' 'Dom' 'Charlie' 'Miles' 'Tom' 'Ollie']
Dom
['Li' 'Dom' 'Charles' 'Miles' 'Tom' 'Ollie']


In [27]:
# 2D Array
import numpy

arr = numpy.array([[1,2,3], [4,5,6]])
print(arr[0])
print(arr[1])

arr[0,1] = 7
print(arr)

[1 2 3]
[4 5 6]
[[1 7 3]
 [4 5 6]]


In [32]:
# Tuples

mytuple = ("Li","Dom","Charlie")

print (mytuple[1])

mylist = []
mytuple1 = ("Li","Dom")
mylist.append(mytuple1)
mytuple2 = ("Charlie","Miles")
mylist.append(mytuple2)
mytuple3 = ("Tom","Ollie")
mylist.append(mytuple3)
print (mylist[1])
print (mylist[1][1])

Dom
('Charlie', 'Miles')
Miles


In [38]:
# Dictionaries / Maps

thisdict = {
    "type": "Student",
    "name": "Li",
    "year": 2003
}
print(thisdict)
print(thisdict["name"])
print(thisdict["year"])

thisdict2 = {
    "Li" : {
        "name": "Li McKenzie",
        "type": "Student",
        "year": 2003
    },
    "Dom" : {
        "name": "Dom Winsborrow",
        "type": "Student",
        "year": 2005
    },
    "Charlie" : {
        "name": "Charlie Birt",
        "type": "Student",
        "year": 2005
    }
}

print(thisdict2)

import pprint as pprint

pprint.pprint(thisdict2)
len(thisdict2)

{'type': 'Student', 'name': 'Li', 'year': 2003}
Li
2003
{'Li': {'name': 'Li McKenzie', 'type': 'Student', 'year': 2003}, 'Dom': {'name': 'Dom Winsborrow', 'type': 'Student', 'year': 2005}, 'Charlie': {'name': 'Charlie Birt', 'type': 'Student', 'year': 2005}}
{'Charlie': {'name': 'Charlie Birt', 'type': 'Student', 'year': 2005},
 'Dom': {'name': 'Dom Winsborrow', 'type': 'Student', 'year': 2005},
 'Li': {'name': 'Li McKenzie', 'type': 'Student', 'year': 2003}}


3

## Functions

## Looping


## If statements